# Generated by Django 3.2.3 on 2021-05-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portifolio',
            old_name='Foto',
            new_name='Imagem',
        ),
    ]
