# Generated by Django 3.2.3 on 2021-05-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_rename_foto_portifolio_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portifolio',
        ),
    ]
