# Generated by Django 3.2.3 on 2021-05-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_portifolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portifolio',
        ),
    ]
