# Generated by Django 3.2.3 on 2021-06-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0013_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
