# Generated by Django 3.2.3 on 2021-06-02 22:54

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_delete_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('Modificado', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('Ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('Bio', models.CharField(max_length=200, verbose_name='Bio')),
                ('Foto', stdimage.models.StdImageField(upload_to='equipe', verbose_name='Foto')),
                ('Facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('Twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('GitHub', models.CharField(default='#', max_length=100, verbose_name='GitHub')),
                ('Instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('LinkedIn', models.CharField(default='#', max_length=100, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
            },
        ),
    ]
