# Generated by Django 3.2.3 on 2021-06-02 22:58

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0015_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('Modificado', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('Ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('Bio', models.CharField(max_length=200, verbose_name='Bio')),
                ('Foto', stdimage.models.StdImageField(upload_to='equipe', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Sociais',
            },
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='Foto',
        ),
    ]
