# Generated by Django 3.2.3 on 2021-06-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0016_auto_20210602_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
