# Generated by Django 3.2.3 on 2021-06-02 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0018_jornada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jornada',
        ),
    ]
