# Generated by Django 3.2.3 on 2021-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0019_delete_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('Modificado', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('Ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('Facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('Twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('Instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Sociais',
            },
        ),
    ]
