# Generated by Django 3.2.3 on 2021-06-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0021_auto_20210609_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
