# Generated by Django 3.2.3 on 2021-06-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0023_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Titulo',
        ),
    ]
